-- List the names of all people who have directed a movie that received a rating of at least 9.0
-- If a person directed more than one movie that received a rating of at least 9.0, 
-- they should only appear in your results once.
-- TODO