-- List the names of all people who starred in a movie released in 2004, ordered by birth year
-- People with the same birth year may be listed in any order
-- If a person appeared in more than one movie in 2004, they should only appear in your results once
-- TODO